### ISSUE TITLE
Add a proper title to the visualization

### ISSUE THREAD

**Issue by abhishek0208** [yboulkaid/osemosys-cloud-visualization#18]
Goal: make it easier to know which scenario the user is visualizing.
- Add the model, version and scenario to the title of the visualization.

**Comment by yboulkaid** [comment]
This has been done in https://github.com/yboulkaid/osemosys-cloud-visualization/pull/23 (and its sister PR in the platform, https://github.com/yboulkaid/osemosys-cloud/pull/183)

For now we only have the model's title (=scenario) and description. The version and model will be added when we have proper support in the platform.
